### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by newhouse** [cayasso/primus.io#24]
Just wondering if this is still maintained or not? I'm about to start using primus, which looks really good to me and still maintained, but I'm a bit worried by what I'm seeing in `primus.io` and some of the other most useful-looking plugins/add-ons like `primus-multiplex`, etc. Maybe I just don't understand their nature, and that they don't really need much updating (only `primus` does)?

**Comment by cayasso** [comment]
Hi @newhouse, just as you say, `primus.io` and the other libraries has been very stable since a long time and hasn't required any major update, this is do mostly to `primus` stability itself which has been changing but has a very stable API and the help of contributors like @lpinca. Most of the issues we have open are feature requests or minor issues. I have been very busy between kids, wife and work so I haven't had the time I would like to fully contribute with new features, etc but as long as `primus` is alive this project will be ;-).
